peso1 = float(input('Digiite o valor peso 1: '))
peso2 = float(input('Digite o valor do peso 2: '))
nota1 = float(input ('Digite a nota 1: '))
nota2 = float (input('Digite  a nota 2: '))
media_pond = ((peso1*nota1)+(peso2*nota2))/(peso1+peso2)
print('A média do aluno é:',media_pond)
